import Head from 'next/head'
import Image from 'next/image'
import React,{useState,useEffect} from 'react'
import { useDispatch, useSelector } from "react-redux";
import { transaction  } from './features/reducers';
export default function Home() {
  
 
  const dispatch = useDispatch();
  const myState = useSelector((state)=>state.transaction)
 
  
  const [value,setValue]=useState({
    desc:'',
    amount:null
  })
  const [data,setData] = useState(myState.data)
  const [income,setIncome] = useState()
  const [some,setSome] = useState(false)
  const handlerChange=(e)=>{
    setValue({
      ...value,
      [e.target.name]:e.target.value
    })
    
  }
  const getIncome=()=>{
    let income=0;
    for(let i =0;i < data.length;i++){
      if(data[i].amount>0){
        income +=Number( data[i].amount)
      }
    }
    return income;
  }
  const getExpense=()=>{
    let expense=0;
    for(let i =0;i < data.length;i++){
      if(data[i].amount<0){
        expense +=Number( data[i].amount)
      }
    }
    return expense;
  }
  const handlerSubmit=(e)=>{
    e.preventDefault()
    dispatch(transaction({
      desc:value.desc,
      amount:Number(value.amount)
    }))
   if(value.desc == '' || value.amount == 'null'){
     alert('All field  is required')
    }
  else{
    setData([...data,value])
    
  }
    setValue({
      desc:'',
      amount:'null'
    })
  }

  const deleteHandler=(e)=>{
   console.log(e,'e')
   setData( data.filter((it,index)=>{
    return index !== e
   })
   )}

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section>
      <div className="bg-gray-100 py-2 ">
        <div className="w-[30%]  mx-auto my-24 font-[500]">
        <h1 className='font-[500]  mb-4 text-2xl'>Expense Tracker By Hamza</h1>
          <h1 className='font-bold'>CURRENT BALANCE</h1>
          <div className="font-[500] text-4xl text-green-400">${getIncome() + getExpense()}<span></span></div>
          <div className="mt-8">
            <div className="flex mb-8 gap-2">
            <div className="w-[50%] flex flex-col bg-white justify-center items-center py-4 rounded-lg">
              <span>INCOME</span>
              <span className='text-green-400'>+${getIncome()}</span>
            </div>
            <div className="w-[50%] flex flex-col bg-white justify-center items-center py-4 rounded-lg">
              <span>EXPENSE</span>
              <span className='text-red-400'>-${Math.abs(getExpense())}</span>
            </div>
            </div>
            <h1 className='text-xl font-bold'>Transaction History</h1>
            <hr className='bg-gray-500 h-[2px]'/>
           <div className="flex flex-col my-4 gap-2">
              {data.map((items,index)=>(
              <span key={index} className='rounded-lg flex justify-between py-2 px-2 bg-white'>
                <h1>{items.desc}</h1>
               <div className="flex gap-2 items-center">
               <h1 className={items.amount<0?'text-red-400':'text-green-400'}>{items.amount<0?'-':''}${Math.abs(items.amount)}</h1>
               <h2 onClick={()=>deleteHandler(index)} className='py-1 px-1 bg-red-600 text-white rounded-lg cursor-pointer'>Delete</h2>
               </div>

              </span>
              ))}
            </div>
            <h1 className='text-xl font-bold'>Add New Transaction</h1>
            <hr className='bg-gray-500 h-[2px]'/>
            <form onSubmit={handlerSubmit} className="flex flex-col gap-2">
            <label    htmlFor="">Description</label>
            <input type="text" value={value.desc} onChange={handlerChange} name='desc' className='py-2 rounded-lg px-2 '/>
            <label htmlFor="">Transaction Amount</label>
            <input value={value.amount} name='amount' onChange={handlerChange} type="number"className=' px-2 py-2 rounded-lg'  />
            <button className='mt-4 rounded-lg bg-purple-500 py-2 text-white' type='submit' onClick={()=>setSome(!some)}>Add Transaction</button>
            </form>
          </div>
        </div>
      </div>
    </section>
    </div>
  )
}

