import type { NextPage } from "next";
import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Plant from "../assests/What-Are-Plants.jpg";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faXmark } from "@fortawesome/free-solid-svg-icons";
const Home: NextPage = () => {
  const [nav, setNav] = useState(false);
  const nextHandler=()=>{

  }
  const prevHandler=()=>{

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        
      </section>
    </div>
  );
};

export default Home;
